using DAL.Entities;
using Microsoft.EntityFrameworkCore;

namespace DAL.DataSeeding
{
    public static class ClassProgramCodeDataSeed
    {
        public static void SeedClassProgramCode(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ClassProgramCode>()
                .HasData(
                    new ClassProgramCode() { Id = 1, ProgramCode = "JAVA" },
                    new ClassProgramCode() { Id = 2, ProgramCode = "NET" },
                    new ClassProgramCode() { Id = 3, ProgramCode = "FE" },
                    new ClassProgramCode() { Id = 4, ProgramCode = "Android" },
                    new ClassProgramCode() { Id = 5, ProgramCode = "CPP" },
                    new ClassProgramCode() { Id = 6, ProgramCode = "Angular" },
                    new ClassProgramCode() { Id = 7, ProgramCode = "REACT" },
                    new ClassProgramCode() { Id = 8, ProgramCode = "PRN" },
                    new ClassProgramCode() { Id = 9, ProgramCode = "EMB" },
                    new ClassProgramCode() { Id = 10, ProgramCode = "OST" },
                    new ClassProgramCode() { Id = 11, ProgramCode = "SP" },
                    new ClassProgramCode() { Id = 12, ProgramCode = "TEST" },
                    new ClassProgramCode() { Id = 13, ProgramCode = "IOS" },
                    new ClassProgramCode() { Id = 14, ProgramCode = "COBOL" },
                    new ClassProgramCode() { Id = 15, ProgramCode = "AUT" },
                    new ClassProgramCode() { Id = 16, ProgramCode = "AI" },
                    new ClassProgramCode() { Id = 17, ProgramCode = "DE" },
                    new ClassProgramCode() { Id = 18, ProgramCode = "QA" },
                    new ClassProgramCode() { Id = 19, ProgramCode = "COMTOR" },
                    new ClassProgramCode() { Id = 20, ProgramCode = "DevOps" },
                    new ClassProgramCode() { Id = 21, ProgramCode = "SAP" },
                    new ClassProgramCode() { Id = 22, ProgramCode = "AC" },
                    new ClassProgramCode() { Id = 23, ProgramCode = "TC" },
                    new ClassProgramCode() { Id = 24, ProgramCode = "GOL" },
                    new ClassProgramCode() { Id = 25, ProgramCode = "Flutter" },
                    new ClassProgramCode() { Id = 26, ProgramCode = "ServiceNow" },
                    new ClassProgramCode() { Id = 27, ProgramCode = "PFR_JAVA" },
                    new ClassProgramCode() { Id = 28, ProgramCode = "FJW" },
                    new ClassProgramCode() { Id = 29, ProgramCode = "JWD" },
                    new ClassProgramCode() { Id = 30, ProgramCode = "JSE" },
                    new ClassProgramCode() { Id = 31, ProgramCode = "PAD" },
                    new ClassProgramCode() { Id = 32, ProgramCode = "FED" },
                    new ClassProgramCode() { Id = 33, ProgramCode = "FNW" },
                    new ClassProgramCode() { Id = 34, ProgramCode = "NWD" },
                    new ClassProgramCode() { Id = 35, ProgramCode = "NPD" },
                    new ClassProgramCode() { Id = 36, ProgramCode = "WAT" },
                    new ClassProgramCode() { Id = 37, ProgramCode = "PRD" },
                    new ClassProgramCode() { Id = 38, ProgramCode = "PML" },
                    new ClassProgramCode() { Id = 39, ProgramCode = "ITF" },
                    new ClassProgramCode() { Id = 40, ProgramCode = "FJB" },
                    new ClassProgramCode() { Id = 41, ProgramCode = "OCA" },
                    new ClassProgramCode() { Id = 42, ProgramCode = "BA" },
                    new ClassProgramCode() { Id = 43, ProgramCode = "APM" },
                    new ClassProgramCode() { Id = 44, ProgramCode = "DSA" },
                    new ClassProgramCode() { Id = 45, ProgramCode = "FIF" },
                    new ClassProgramCode() { Id = 46, ProgramCode = "DEE" },
                    new ClassProgramCode() { Id = 47, ProgramCode = "STE" },
                    new ClassProgramCode() { Id = 48, ProgramCode = "Flexcube" },
                    new ClassProgramCode() { Id = 49, ProgramCode = "OCP" },
                    new ClassProgramCode() { Id = 50, ProgramCode = "FUJS" },
                    new ClassProgramCode() { Id = 51, ProgramCode = "CES" },
                    new ClassProgramCode() { Id = 52, ProgramCode = "CLOUD" },
                    new ClassProgramCode() { Id = 53, ProgramCode = "PHP" },
                    new ClassProgramCode() { Id = 54, ProgramCode = "NodeJS" },
                    new ClassProgramCode() { Id = 55, ProgramCode = "ASE" },
                    new ClassProgramCode() { Id = 56, ProgramCode = "MPP" },
                    new ClassProgramCode() { Id = 57, ProgramCode = "DATA" },
                    new ClassProgramCode() { Id = 58, ProgramCode = "Sitecore" },
                    new ClassProgramCode() { Id = 59, ProgramCode = "MAT" },
                    new ClassProgramCode() { Id = 60, ProgramCode = "AND" },
                    new ClassProgramCode() { Id = 61, ProgramCode = "ADR" },
                    new ClassProgramCode() { Id = 62, ProgramCode = "JAVA" },
                    new ClassProgramCode() { Id = 63, ProgramCode = "Mobile" },
                    new ClassProgramCode() { Id = 64, ProgramCode = "GST_JAVA" },
                    new ClassProgramCode() { Id = 65, ProgramCode = "LITE_CPP" },
                    new ClassProgramCode() { Id = 66, ProgramCode = "WinApp" },
                    new ClassProgramCode() { Id = 67, ProgramCode = "Magento" },
                    new ClassProgramCode() { Id = 68, ProgramCode = "Python" },
                    new ClassProgramCode() { Id = 69, ProgramCode = "RN" },
                    new ClassProgramCode() { Id = 70, ProgramCode = "FUKS" },
                    new ClassProgramCode() { Id = 71, ProgramCode = "RPA" },
                    new ClassProgramCode() { Id = 72, ProgramCode = "Erlang" },
                    new ClassProgramCode() { Id = 73, ProgramCode = "Golang" },
                    new ClassProgramCode() { Id = 74, ProgramCode = "C++/Linux" },
                    new ClassProgramCode() { Id = 75, ProgramCode = "AEM" },
                    new ClassProgramCode() { Id = 76, ProgramCode = "GST_EMB" },
                    new ClassProgramCode() { Id = 77, ProgramCode = "GST_NET" },
                    new ClassProgramCode() { Id = 78, ProgramCode = "JP" }
                );
        }
    }
}
